### ISSUE TITLE
Enchanted item name must contain base item name as substring.

### ISSUE THREAD

**Issue by entvidya** [Jampi0n/Skyrim-LeveledLoot#2]
Hi, I've been interested in trying this patcher, I found it through the Synthesis repository section. However, I have not been able to run it on my load order. I get the error message in the title. Here is the output from the patcher:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Exception: Enchanted item name must contain base item name as substring.
>    at LeveledLoot.Enchanter.RegisterArmorEnchantments(ItemType itemType, IFormLink`1 itemLink, IFormLink`1 enchantmentLists, Int32 tier) in C:\Users\alexa\AppData\Local\Temp\Synthesis\jcl2nzfn.eko\Git\hkcovxzz.xwp\Runner\Skyrim-LeveledLoot\Enchanter.cs:line 431
>    at LeveledLoot.ArmorConfig..ctor() in C:\Users\alexa\AppData\Local\Temp\Synthesis\jcl2nzfn.eko\Git\hkcovxzz.xwp\Runner\Skyrim-LeveledLoot\ArmorConfig.cs:line 283
>    at System.RuntimeType.CreateInstanceOfT()
>    --- End of inner exception stack trace ---
>    at System.RuntimeType.CreateInstanceOfT()
>    at System.Activator.CreateInstance[T]()
>    at LeveledLoot.LootConfig`1.Run() in C:\Users\alexa\AppData\Local\Temp\Synthesis\jcl2nzfn.eko\Git\hkcovxzz.xwp\Runner\Skyrim-LeveledLoot\Program.cs:line 90
>    at LeveledLoot.Program.RunPatch(IPatcherState`2 state) in C:\Users\alexa\AppData\Local\Temp\Synthesis\jcl2nzfn.eko\Git\hkcovxzz.xwp\Runner\Skyrim-LeveledLoot\Program.cs:line 69
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass16_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 106
> --- End of stack trace from previous location ---
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 631
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass45_0.<<Run>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 496
> --- End of stack trace from previous location ---
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.HandleOnShutdown(Func`1 a) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 881
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 484
>    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass44_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 456

Any guidance you could offer would be greatly appreciated. If this is something I've done wrong or that I can correct, I'd love to, but I can't really understand what the message is asking me to do.

**Comment by Jampi0n** [comment]
Sorry for the late reply. I made this patcher mostly for me, so the error message isn't so helpful.

The patcher is going through leveled lists containing enchanted items in order to find all different enchantments and their names.
For example, it would find the enchanted item "Dwarven Gauntlets of Minor Archery" for the base item "Dwarven Gauntlets" and conclude that the enchantment name is "of Minor Archery". If the enchanted item name does not contain the item name of the base item, for example "Dwarven Bracers of Minor Archery", it can no longer figure out the name of the enchantment.

I've changed the error message to include which item and enchanted item do not match. You can update the patcher and run it again to see which items are causing problems.
Usually, all enchanted items are supposed to contain the base item name in their name, so if this error appears there might be some naming errors in your load order and you can fix them. Vanilla Skyrim for instance uses "Dwarven Bracers" for enchanted versions of "Dwarven Gauntlets", which is why this patcher needs the unofficial patch to work. Perhaps a mod you use is reverting those.
